version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

    ports:
      - "5432:5432"
