// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: collector/collector.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectKnobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CollectKnobsRequest) Reset() {
	*x = CollectKnobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_collector_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsRequest) ProtoMessage() {}

func (x *CollectKnobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsRequest.ProtoReflect.Descriptor instead.
func (*CollectKnobsRequest) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{0}
}

type CollectKnobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knobs []*CollectKnobsResponse_Knob `protobuf:"bytes,1,rep,name=knobs,proto3" json:"knobs,omitempty"`
}

func (x *CollectKnobsResponse) Reset() {
	*x = CollectKnobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_collector_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsResponse) ProtoMessage() {}

func (x *CollectKnobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsResponse.ProtoReflect.Descriptor instead.
func (*CollectKnobsResponse) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{1}
}

func (x *CollectKnobsResponse) GetKnobs() []*CollectKnobsResponse_Knob {
	if x != nil {
		return x.Knobs
	}
	return nil
}

type CollectKnobsResponse_Knob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//
	//	*CollectKnobsResponse_Knob_StrValue
	//	*CollectKnobsResponse_Knob_FloatValue
	//	*CollectKnobsResponse_Knob_BoolValue
	Value isCollectKnobsResponse_Knob_Value `protobuf_oneof:"value"`
}

func (x *CollectKnobsResponse_Knob) Reset() {
	*x = CollectKnobsResponse_Knob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collector_collector_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectKnobsResponse_Knob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectKnobsResponse_Knob) ProtoMessage() {}

func (x *CollectKnobsResponse_Knob) ProtoReflect() protoreflect.Message {
	mi := &file_collector_collector_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectKnobsResponse_Knob.ProtoReflect.Descriptor instead.
func (*CollectKnobsResponse_Knob) Descriptor() ([]byte, []int) {
	return file_collector_collector_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CollectKnobsResponse_Knob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *CollectKnobsResponse_Knob) GetValue() isCollectKnobsResponse_Knob_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *CollectKnobsResponse_Knob) GetStrValue() string {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (x *CollectKnobsResponse_Knob) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *CollectKnobsResponse_Knob) GetBoolValue() bool {
	if x, ok := x.GetValue().(*CollectKnobsResponse_Knob_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isCollectKnobsResponse_Knob_Value interface {
	isCollectKnobsResponse_Knob_Value()
}

type CollectKnobsResponse_Knob_StrValue struct {
	StrValue string `protobuf:"bytes,2,opt,name=str_value,json=strValue,proto3,oneof"`
}

type CollectKnobsResponse_Knob_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type CollectKnobsResponse_Knob_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*CollectKnobsResponse_Knob_StrValue) isCollectKnobsResponse_Knob_Value() {}

func (*CollectKnobsResponse_Knob_FloatValue) isCollectKnobsResponse_Knob_Value() {}

func (*CollectKnobsResponse_Knob_BoolValue) isCollectKnobsResponse_Knob_Value() {}

var File_collector_collector_proto protoreflect.FileDescriptor

var file_collector_collector_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xdb, 0x01,
	0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x6b, 0x6e, 0x6f, 0x62, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4b, 0x6e, 0x6f, 0x62, 0x52, 0x05, 0x6b, 0x6e, 0x6f,
	0x62, 0x73, 0x1a, 0x86, 0x01, 0x0a, 0x04, 0x4b, 0x6e, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21,
	0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x5c, 0x0a, 0x09, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62, 0x73, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4b, 0x6e, 0x6f, 0x62,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collector_collector_proto_rawDescOnce sync.Once
	file_collector_collector_proto_rawDescData = file_collector_collector_proto_rawDesc
)

func file_collector_collector_proto_rawDescGZIP() []byte {
	file_collector_collector_proto_rawDescOnce.Do(func() {
		file_collector_collector_proto_rawDescData = protoimpl.X.CompressGZIP(file_collector_collector_proto_rawDescData)
	})
	return file_collector_collector_proto_rawDescData
}

var file_collector_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_collector_collector_proto_goTypes = []interface{}{
	(*CollectKnobsRequest)(nil),       // 0: collector.CollectKnobsRequest
	(*CollectKnobsResponse)(nil),      // 1: collector.CollectKnobsResponse
	(*CollectKnobsResponse_Knob)(nil), // 2: collector.CollectKnobsResponse.Knob
}
var file_collector_collector_proto_depIdxs = []int32{
	2, // 0: collector.CollectKnobsResponse.knobs:type_name -> collector.CollectKnobsResponse.Knob
	0, // 1: collector.Collector.CollectKnobs:input_type -> collector.CollectKnobsRequest
	1, // 2: collector.Collector.CollectKnobs:output_type -> collector.CollectKnobsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_collector_collector_proto_init() }
func file_collector_collector_proto_init() {
	if File_collector_collector_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collector_collector_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_collector_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collector_collector_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectKnobsResponse_Knob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_collector_collector_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CollectKnobsResponse_Knob_StrValue)(nil),
		(*CollectKnobsResponse_Knob_FloatValue)(nil),
		(*CollectKnobsResponse_Knob_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collector_collector_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collector_collector_proto_goTypes,
		DependencyIndexes: file_collector_collector_proto_depIdxs,
		MessageInfos:      file_collector_collector_proto_msgTypes,
	}.Build()
	File_collector_collector_proto = out.File
	file_collector_collector_proto_rawDesc = nil
	file_collector_collector_proto_goTypes = nil
	file_collector_collector_proto_depIdxs = nil
}
